env:
  browser: true
  es6: true
extends:
  - eslint:recommended
  - plugin:react/recommended
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
rules:
  indent:
    - error
    - 4
    - SwitchCase: 1
  linebreak-style: 0
  quotes:
    - error
    - double
  semi:
    - error
    - always
  no-console: 0
  curly: error
  strict: [error, global]